### ISSUE TITLE
JSON from WOOD Dump fails parsing

### ISSUE THREAD

**Issue by tolauwae** [TOPLLab/WARDuino-VSCode#7]
JSON parse fails for both the emulator and the embedded versions.

However, telnet receives a valid json on (0x60):

```json
{
   "pc":"0x56282d91973c",
   "start":[
      "0x56282d9196a0"
   ],
   "breakpoints":[
      
   ],
   "stack":[
      {
         "idx":0,
         "type":"i32",
         "value":1000
      }
   ],
   "callstack":[
      {
         "type":0,
         "fidx":"0x4",
         "sp":-1,
         "fp":-1,
         "block_key":"(nil)",
         "ra":"0x56282d91970f"
      },
      {
         "type":3,
         "fidx":"0x0",
         "sp":0,
         "fp":0,
         "block_key":"0x56282d919730",
         "ra":"0x56282d919732"
      }
   ],
   "globals":[
      {
         "idx":0,
         "type":"i32",
         "value":23
      },
      {
         "idx":1,
         "type":"i32",
         "value":1
      },
      {
         "idx":2,
         "type":"i32",
         "value":0
      }
   ],
   "table":{
      "max":0,
      "init":0,
      "elements":[
         
      ]
   },
   "memory":{
      "pages":0,
      "max":0,
      "init":0,
      "bytes":[
         
      ]
   },
   "br_table":{
      "size":"0x100",
      "labels":[
         
      ]
   }
}
```

**Comment by tolauwae** [comment]
Seems to be caused by the `write` calls in `Debugger::woodDump`.
This appears to be [a known issue](https://github.com/TOPLLab/WARDuino/blob/feat/wood/src/Debug/debugger.cpp#L486) @carllocos?

**Comment by carllocos** [comment]
Something weird is indeed happening due to the `write`.
Weirdly in telnet, we receive a JSON but without the content that has been send through a `write` call (e.g., labels, memory, etc.) but if I read the dump using my own [socket-based reading tool](https://github.com/carllocos/out-of-things/blob/c630305dbbe8e3dcb5cb59fd18f7b14c7d52a4b1/warduino/warduino.py#L61) (the function is the one responsible to read from the socket) I successfully receive all the sent content.

**Comment by tolauwae** [comment]
I'll run some tests with your python script. I want to figure out what is going on here, because optimistically changing the `write` to `dprintf` with casts (`reinterpret_cast<const char *>`) results in unhandled exceptions on the ESP32 (though not with the emulator).

**Comment by carllocos** [comment]
I don't think you can use the `dprintf` because that will read the binary as a string potentially causing an undefined behaviour given that the binary was never null-terminated.

A potential solution is to convert the binary to a hexa string and send the string through a regular `dprintf`. However, this approach requires to allocate memory which is preferably avoided due to the scarce memory.

**Comment by tolauwae** [comment]
I had forgotten I could just use the python script for now. Not an issue anymore.
